### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gentlementlegen**

### CODE REVIEW

**Comment by 0x4007** [comment]
> /[start | stop]

This syntax is not great. We should iterate on this. We should list them as separate commands (seems more clear.)

**Comment by gentlementlegen** [comment]
@0x4007 Can be done just that the current design only allows for one command per `uses` configuration element, c.f. https://github.com/ubiquity/ubiquibot-kernel/blob/570b68e18639e9c38a90872cfb8cbfbbdf661481/src/github/types/plugin-configuration.ts#L60
We could consider support an array of `command` instead of just one element.

**Comment by 0x4007** [comment]
One idea is to list it as:

`/start /stop` instead

The preceding `/` makes it clear that it is its own command.

**Comment by gentlementlegen** [comment]
@0x4007 This should be solved by our new manifest file which allows for many commands to be listed.

**Pull request closed without merging**
